### ISSUE TITLE
popups that overlap with album art dont get cleared

### ISSUE THREAD

**Issue by rmsthebest** [mierak/rmpc#21] opened 2024-07-29 13:04 UTC
reproduce:
1. Go to queue view (format the window quite narrow)
2. press "D" to clear queue
3. Select Accept
4. The popup window only gets cleared partially, the part covering album art is sticky until some other redraw such as a window resize happens

**Comment by mierak** [comment] 2024-07-29 14:11
Hey, thanks for the report.
I just merged #22 can you try again if the problem is fixed?

**Closed** 2024-07-29 14:10 UTC

**Comment by rmsthebest** [comment] 2024-07-29 14:33
I can confirm it works now.

Unrelated, but if you do end up creating a pkgbuild or something similar: libz-ng-sys requires cmake to build so remember to add that to the depends list
